#!/bin/bash

if [ -f "./react-codemod/transforms/class.js" -a -f "./react-codemod/transforms/React-PropTypes-to-prop-types.js" -a -f "./react-codemod/transforms/ReactNative-View-propTypes.js" ]
then
    echo "Found necessary files in ./react-codemod." 
else
    echo "Directory ./react-codemod does not exist."
    echo "Cloning react-codemod into current directory."
    git clone https://github.com/reactjs/react-codemod.git
fi

echo "Performing react transformations"

jscodeshift -t ./react-codemod/transforms/class.js node_modules/react-native-multi-slider
jscodeshift -t ./react-codemod/transforms/React-PropTypes-to-prop-types.js node_modules/react-native-multi-slider
jscodeshift -t ./react-codemod/transforms/ReactNative-View-propTypes.js node_modules/react-native-multi-slider

unameOut="$(uname -s)"
mac="Mac"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac

if ! grep -Fq "var { ViewPropTypes } = require('react-native');" node_modules/react-native-multi-slider/mockProps.js
then
    if [ "$machine" == "$mac" ]
    then
        sed -i "" $'s|var ReactNative = require(\'react-native\');|var ReactNative = require(\'react-native\');\\\n var { ViewPropTypes } = require(\'react-native\');|' node_modules/react-native-multi-slider/mockProps.js
        sed -i "" $'s|var ReactNative = require(\'react-native\');|var ReactNative = require(\'react-native\');\\\n var { ViewPropTypes } = require(\'react-native\');|' node_modules/react-native-multi-slider/Slider.js
    else
        sed -i $'s|var ReactNative = require(\'react-native\');|var ReactNative = require(\'react-native\');\\\n var { ViewPropTypes } = require(\'react-native\');|' node_modules/react-native-multi-slider/mockProps.js
        sed -i $'s|var ReactNative = require(\'react-native\');|var ReactNative = require(\'react-native\');\\\n var { ViewPropTypes } = require(\'react-native\');|' node_modules/react-native-multi-slider/Slider.js
    fi
fi